services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Theater
      - SPRING_DATASOURCE_USERNAME=matt
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - movietickeing-postgres
      - movietickeing-react 
  api:
    build: 
      context: api
      args:
        REACT_APP_MOVIEDB_KEY: ${REACT_APP_MOVIEDB_KEY}
    ports:
      - 3030:3030
    networks:
      - movietickeing-react 
  frontend:
    build:
      context: frontend
      args:
        REACT_APP_MOVIE_USER: ${REACT_APP_MOVIE_USER}
        REACT_APP_MOVIE_PASSWORD: ${REACT_APP_MOVIE_PASSWORD}
    ports:
      - 80:80
    depends_on:
      - backend
      - api
    networks:
      - movietickeing-react
  db:
    image: postgres
    restart: always
    volumes:
      - movie-data:/var/lib/postgresql/data
    networks:
      - movietickeing-postgres
    environment:
      - POSTGRES_DB=Theater
      - POSTGRES_USER=matt
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
volumes:
  movie-data:
networks:
  movietickeing-react:
  movietickeing-postgres: